"""Migrations must produce the schema the models describe.

Autogenerated migrations drift from models quietly: a column added to a model without a
migration works perfectly in tests (which use `create_all`) and fails on deploy. This
builds a database through Alembic alone and compares it to the model metadata.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic.config import Config
from sqlalchemy import create_engine, inspect

import app.models  # noqa: F401 - registers models on Base.metadata
from alembic import command
from app.config.settings import BACKEND_ROOT
from app.db.base import Base

#: Alembic renders these as part of the JSON/JSONB variant; a column type mismatch here
#: is expected and not meaningful, so only names and nullability are compared.
_IGNORED_TABLES = {"alembic_version"}


@pytest.fixture(scope="module")
def migrated_schema(tmp_path_factory: pytest.TempPathFactory) -> dict[str, dict[str, bool]]:
    db_path = tmp_path_factory.mktemp("migrations") / "migrated.db"
    url = f"sqlite:///{db_path}"

    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    config.set_main_option("sqlalchemy.url", url)
    command.upgrade(config, "head")

    engine = create_engine(url)
    inspector = inspect(engine)
    schema = {
        table: {col["name"]: bool(col["nullable"]) for col in inspector.get_columns(table)}
        for table in inspector.get_table_names()
        if table not in _IGNORED_TABLES
    }
    engine.dispose()
    return schema


def test_migration_creates_every_model_table(migrated_schema: dict[str, dict[str, bool]]) -> None:
    assert set(migrated_schema) == set(Base.metadata.tables)


def test_migration_columns_match_the_models(migrated_schema: dict[str, dict[str, bool]]) -> None:
    for name, table in Base.metadata.tables.items():
        migrated = migrated_schema[name]
        expected = {col.name: col.nullable for col in table.columns}
        assert migrated == expected, f"{name} drifted between models and migrations"


def test_exactly_one_migration_head() -> None:
    """Two heads mean a merge is needed and `upgrade head` would fail on deploy."""
    from alembic.script import ScriptDirectory

    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    assert len(ScriptDirectory.from_config(config).get_heads()) == 1


def test_migrations_do_not_hardcode_a_database_url() -> None:
    """Credentials must come from the environment, never from a tracked file."""
    ini = (BACKEND_ROOT / "alembic.ini").read_text(encoding="utf-8")
    assert "sqlalchemy.url =" not in ini


def test_no_orphaned_migration_files() -> None:
    versions = list((BACKEND_ROOT / "alembic" / "versions").glob("*.py"))
    assert versions, "no migrations found"
    for path in versions:
        assert Path(path).read_text(encoding="utf-8").count("def upgrade()") == 1
