"""conversation messages

Revision ID: 2a4c616ce2d7
Revises: a1b611cd3d10
Create Date: 2026-09-12 22:45:29.506882
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

# PortableJSON (app/db/base.py) autogenerates as a JSON/JSONB variant, which renders
# references to both of these.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql  # noqa: F401

from alembic import op

revision: str = "2a4c616ce2d7"
down_revision: str | None = "a1b611cd3d10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("requirement_id", sa.String(length=36), nullable=True),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("body", sa.String(length=4000), nullable=False),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_message_application_created", ["application_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_message_channel_created", ["channel", "created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_messages_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_messages_created_at"), ["created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_created_at"))
        batch_op.drop_index(batch_op.f("ix_messages_application_id"))
        batch_op.drop_index("ix_message_channel_created")
        batch_op.drop_index("ix_message_application_created")

    op.drop_table("messages")
    # ### end Alembic commands ###
