"""domain core

Revision ID: a1b611cd3d10
Revises:
Create Date: 2026-09-12 20:22:52.645257
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

# PortableJSON (app/db/base.py) autogenerates as a JSON/JSONB variant, which renders
# references to both of these.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql  # noqa: F401

from alembic import op

revision: str = "a1b611cd3d10"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("external_reference", sa.String(length=64), nullable=False),
        sa.Column("borrower_name", sa.String(length=200), nullable=False),
        sa.Column("business_name", sa.String(length=200), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_applications_external_reference"), ["external_reference"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_applications_phone_number"), ["phone_number"], unique=False
        )

    op.create_table(
        "document_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("requirement_id", sa.String(length=36), nullable=True),
        sa.Column("application_id", sa.String(length=36), nullable=True),
        sa.Column("application_reference", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            "ix_event_document_created", ["document_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_event_requirement", ["requirement_id"], unique=False)
        batch_op.create_index("ix_event_type_created", ["event_type", "created_at"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_type", sa.String(length=48), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=64), nullable=True),
        sa.Column("dedupe_key", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_job_claim", ["status", "available_at"], unique=False)
        batch_op.create_index("ix_job_dedupe", ["job_type", "dedupe_key"], unique=False)

    op.create_table(
        "document_requirements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("document_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("submission_count", sa.Integer(), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleared_by_document_id", sa.String(length=36), nullable=True),
        sa.Column("first_time_cleared", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id", "document_type", name="uq_requirement_per_type"),
    )
    with op.batch_alter_table("document_requirements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_requirements_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index("ix_requirement_status", ["status"], unique=False)

    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("requirement_id", sa.String(length=36), nullable=False),
        sa.Column("submission_index", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("declared_mime_type", sa.String(length=128), nullable=True),
        sa.Column("detected_mime_type", sa.String(length=128), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("is_encrypted", sa.Boolean(), nullable=False),
        sa.Column("password_attempts", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["requirement_id"], ["document_requirements.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("requirement_id", "submission_index", name="uq_submission_index"),
        sa.UniqueConstraint("storage_key"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index("ix_document_status", ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_documents_requirement_id"), ["requirement_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_documents_sha256"), ["sha256"], unique=False)

    op.create_table(
        "document_extractions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_version", sa.String(length=64), nullable=True),
        sa.Column("text_layer", sa.String(length=16), nullable=False),
        sa.Column(
            "raw_result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "normalized_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "field_confidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_extractions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_extractions_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reviewer_action", sa.String(length=32), nullable=True),
        sa.Column("reviewer_note", sa.String(length=1000), nullable=True),
        sa.Column("reviewer_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index("ix_review_status_created", ["status", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviews_document_id"), ["document_id"], unique=False)

    op.create_table(
        "validation_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("primary_reason_code", sa.String(length=64), nullable=True),
        sa.Column(
            "secondary_reason_codes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("composite_confidence", sa.Float(), nullable=True),
        sa.Column("field_score", sa.Float(), nullable=True),
        sa.Column("rule_coverage", sa.Float(), nullable=True),
        sa.Column(
            "rule_results",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("customer_message", sa.String(length=2000), nullable=True),
        sa.Column("rules_version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("validation_results", schema=None) as batch_op:
        batch_op.create_index("ix_validation_outcome", ["outcome"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_validation_results_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_validation_results_primary_reason_code"),
            ["primary_reason_code"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("validation_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_validation_results_primary_reason_code"))
        batch_op.drop_index(batch_op.f("ix_validation_results_document_id"))
        batch_op.drop_index("ix_validation_outcome")

    op.drop_table("validation_results")
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_document_id"))
        batch_op.drop_index("ix_review_status_created")

    op.drop_table("reviews")
    with op.batch_alter_table("document_extractions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_extractions_document_id"))

    op.drop_table("document_extractions")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_sha256"))
        batch_op.drop_index(batch_op.f("ix_documents_requirement_id"))
        batch_op.drop_index("ix_document_status")

    op.drop_table("documents")
    with op.batch_alter_table("document_requirements", schema=None) as batch_op:
        batch_op.drop_index("ix_requirement_status")
        batch_op.drop_index(batch_op.f("ix_document_requirements_application_id"))

    op.drop_table("document_requirements")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_job_dedupe")
        batch_op.drop_index("ix_job_claim")

    op.drop_table("jobs")
    with op.batch_alter_table("document_events", schema=None) as batch_op:
        batch_op.drop_index("ix_event_type_created")
        batch_op.drop_index("ix_event_requirement")
        batch_op.drop_index("ix_event_document_created")
        batch_op.drop_index(batch_op.f("ix_document_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_document_events_created_at"))

    op.drop_table("document_events")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_phone_number"))
        batch_op.drop_index(batch_op.f("ix_applications_external_reference"))

    op.drop_table("applications")
    # ### end Alembic commands ###
