"""Object storage.

`StorageProvider` is the seam; `LocalFileStorage` is the MVP implementation and a GCS
implementation would satisfy the same protocol (ADR-002/ADR-005).

Storage is private by construction: nothing here serves files over HTTP, and the storage
directory is never mounted as static content. Reads go through the API, which requires a
signed, short-lived token. There is no code path that produces a public document URL.
"""

from __future__ import annotations

import hashlib
import uuid
from collections.abc import Iterator
from datetime import UTC, datetime
from pathlib import Path
from typing import BinaryIO, Protocol

from app.config.settings import get_settings


class StorageError(RuntimeError):
    pass


def new_storage_key(prefix: str = "documents") -> str:
    """An opaque, generated key.

    Never derived from the uploaded filename. A caller-controlled name is a
    path-traversal and overwrite vector, and it also leaks the customer's own file naming
    into our storage (`PRODUCT_SPEC.md` section 12). The `.bin` suffix is deliberate: the
    stored object carries no extension that any tool would act on.
    """
    now = datetime.now(UTC)
    return f"{prefix}/{now:%Y/%m}/{uuid.uuid4().hex}.bin"


class StorageProvider(Protocol):
    def write(self, key: str, chunks: Iterator[bytes]) -> int: ...

    def read(self, key: str) -> bytes: ...

    def open(self, key: str) -> BinaryIO: ...

    def exists(self, key: str) -> bool: ...

    def delete(self, key: str) -> None: ...


class LocalFileStorage:
    def __init__(self, root: Path | None = None) -> None:
        self.root = (root or get_settings().storage_dir).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        """Resolve a key to a path, refusing anything that escapes the root.

        Keys are generated by `new_storage_key`, so traversal should be impossible --
        but "should be impossible" is how directory traversal bugs are written. The
        check costs nothing and holds even if a future caller passes a key from
        elsewhere.
        """
        candidate = (self.root / key).resolve()
        if not candidate.is_relative_to(self.root):
            raise StorageError(f"storage key escapes the storage root: {key!r}")
        return candidate

    def write(self, key: str, chunks: Iterator[bytes]) -> int:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        written = 0
        with path.open("wb") as fh:
            for chunk in chunks:
                fh.write(chunk)
                written += len(chunk)
        return written

    def read(self, key: str) -> bytes:
        return self._path(key).read_bytes()

    def open(self, key: str) -> BinaryIO:
        return self._path(key).open("rb")

    def exists(self, key: str) -> bool:
        return self._path(key).exists()

    def delete(self, key: str) -> None:
        """Remove an object. Used by the retention purge path.

        Missing objects are not an error: purging is idempotent by design, because a
        retention job that fails halfway must be safe to re-run.
        """
        self._path(key).unlink(missing_ok=True)

    def sha256(self, key: str) -> str:
        digest = hashlib.sha256()
        with self.open(key) as fh:
            for chunk in iter(lambda: fh.read(65536), b""):
                digest.update(chunk)
        return digest.hexdigest()


def get_storage() -> StorageProvider:
    return LocalFileStorage()
